services:
  livrosgratuitos-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livrosgratuitos-back
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env